# Generated by Django 5.2.4 on 2025-08-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariation',
            unique_together={('product', 'size')},
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='size',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], max_length=10),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='weight',
        ),
    ]
